[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "nodejs_22"
]

[phases.install]
cmds = [
    "composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction",
    "npm ci --include=dev"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public public/index.php"
